{
  perSystem =
    { pkgs, lib, ... }:
    let
      gems = {
        jekyll = "4.4.1";
        sass-embedded = "1.80.4";
        google-protobuf = "4.28.3";
      };

      plugins = {
        jekyll-feed = "0.17";
      };

      lines = 
        indent: gems:
        lib.concatStringsSep "\n" (
          lib.mapAttrsToList (name: version: ''${indent}gem "${name}", "~> ${version}"'') gems
        );

      gemfile = pkgs.writeText "Gemfile" ''
        # This file is automatically generated by nix/gems.nix. Do not edit!
        source "https://rubygems.org"

        # Gem dependencies to be installed
        ${lines "" gems}

        # Jekyll plugins
        group :jekyll_plugins do
        ${lines "  " plugins}
        end
      '';
    in
    {
      packages.gems = pkgs.bundlerEnv {
        name = "blog-bundler";
        inherit (pkgs) ruby;
        gemfile = ../Gemfile;
        lockfile = ../Gemfile.lock;
        gemset = ../gemset.nix;
      };

      packages.generate = pkgs.writeShellApplication {
        name = "generate";
        runtimeInputs = [
          pkgs.bundler
          pkgs.bundix
          pkgs.gcc
          pkgs.gnumake
          pkgs.pkg-config
          pkgs.zlib.dev
          pkgs.libxml2.dev
          pkgs.libxslt.dev
        ];
        text = ''
          rm -f gemset.nix Gemfile Gemfile.lock .bundle/config
          install -m 644 ${gemfile} Gemfile

          export BUNDLE_PATH=vendor
          export BUNDLE_PATH=vendor
          export BUNDLE_CACHE_ALL=true
          export BUNDLE_NO_INSTALL=true
          export BUNDLE_FORCE_RUBY_PLATFORM=true

          bundler update
          bundler lock
          bundler package
          bundix --magic
          rm -rf vendor
        '';
      };
    };
}
