# This file is automatically generated by nix/gems.nix. Do not edit!
source "https://rubygems.org"

# Gem dependencies to be installed
gem "google-protobuf", "~> 4.28.3"
gem "jekyll", "~> 4.4.1"
gem "sass-embedded", "~> 1.80.4"

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end
