local theme, colorscheme, background, lualine_theme, setup = arg[1], arg[2], arg[3], arg[4], arg[5]

vim.o.termguicolors = true
vim.o.background = background

vim.cmd(setup or "")
vim.cmd.colorscheme(colorscheme)

require("nvim-web-devicons").setup()
require("lualine").setup({ options = { theme = lualine_theme, section_separators = "", component_separators = "" } })

local editor = {
	"Normal",
	"Visual",
	"Cursor",
	"LineNr",
	"CursorLineNr",
	"CursorLine",
	"Search",
	"CurSearch",
	"Pmenu",
	"PmenuSel",
	"NormalFloat",
	"FloatBorder",
	"ErrorMsg",
	"WarningMsg",
	"DevIconMd",
	"DevIconTxt",
	"Directory",
}

local captures = {}
for _, file in ipairs(vim.api.nvim_get_runtime_file("parser/*.so", true)) do
	local ok, query = pcall(vim.treesitter.query.get, vim.fn.fnamemodify(file, ":t:r"), "highlights")
	if ok and query then
		for _, capture in ipairs(query.captures) do
			if not capture:match("^_") then
				captures[capture] = true
			end
		end
	end
end
captures = vim.tbl_keys(captures)
table.sort(captures)

local function resolve(group)
	return vim.api.nvim_get_hl(0, { id = vim.fn.synIDtrans(vim.fn.hlID(group)), link = false })
end

local function hex(color)
	return ("#%06x"):format(color)
end

local normal = resolve("Normal")

local function declarations(hl)
	local css = {}
	if hl.fg then
		table.insert(css, "color: " .. hex(hl.fg))
	end
	if hl.bg and hl.bg ~= normal.bg then
		table.insert(css, "background-color: " .. hex(hl.bg))
	end
	if hl.bold then
		table.insert(css, "font-weight: bold")
	end
	if hl.italic then
		table.insert(css, "font-style: italic")
	end
	local lines = {}
	if hl.underline or hl.undercurl then
		table.insert(lines, "underline")
	end
	if hl.strikethrough then
		table.insert(lines, "line-through")
	end
	if #lines > 0 then
		table.insert(css, "text-decoration: " .. table.concat(lines, " "))
	end
	return css
end

local function colors(hl)
	if hl.reverse then
		return hl.bg or normal.bg, hl.fg or normal.fg
	end
	return hl.fg, hl.bg
end

local function section(name, mode)
	local hl = vim.api.nvim_get_hl(0, { name = ("lualine_%s_%s"):format(name, mode), link = false })
	if next(hl) then
		return hl
	end
	local borrowed = ({ x = "c", y = "b", z = "a" })[name]
	if borrowed then
		return section(borrowed, mode)
	end
	return section(name, "normal")
end

local function css_string(text)
	return text == "" and '""' or ('"\\%x"'):format(vim.fn.char2nr(text))
end

local function lualine(mode)
	local separators = require("lualine").get_config().options.section_separators
	local vars = {}
	local sections = {}
	for _, name in ipairs({ "a", "b", "c", "x", "y", "z" }) do
		local hl = section(name, mode)
		sections[name] = hl
		table.insert(vars, ("--%s-fg: %s; --%s-bg: %s;"):format(name, hex(hl.fg), name, hex(hl.bg)))
		if hl.bold then
			table.insert(vars, ("--%s-weight: bold;"):format(name))
		end
	end
	for _, pair in ipairs({
		{ "a", "b", "left" },
		{ "b", "c", "left" },
		{ "c", "x", "right" },
		{ "x", "y", "right" },
		{ "y", "z", "right" },
	}) do
		local from, to, side = unpack(pair)
		local drawn = sections[from].bg ~= sections[to].bg
		table.insert(vars, ("--%s%s: %s;"):format(from, to, drawn and css_string(separators[side]) or '""'))
	end
	return ('  .lualine[data-mode="%s"] { %s }'):format(mode, table.concat(vars, " "))
end

local function fg(group)
	local color = resolve(group).fg
	return color and hex(color)
end
local derived = {
	[0] = hex(normal.bg),
	fg("DiagnosticError"),
	fg("DiagnosticOk"),
	fg("DiagnosticWarn"),
	fg("DiagnosticInfo"),
	fg("Keyword"),
	fg("DiagnosticHint"),
	hex(normal.fg),
	fg("Comment"),
}
local function ansi(i)
	local color = vim.g["terminal_color_" .. i]
	if type(color) == "string" and color:match("^#%x%x%x%x%x%x$") then
		return color:lower()
	end
	return derived[i] or derived[i - 8] or hex(normal.fg)
end

local out = { ("// %s, generated by _nvim/theme.lua"):format(theme), ('[data-theme="%s"] {'):format(theme) }
for i, name in ipairs({ "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white" }) do
	table.insert(out, ("  --%s: %s; --bright-%s: %s;"):format(name, ansi(i - 1), name, ansi(i + 7)))
end
for _, group in ipairs(editor) do
	local fg, bg = colors(resolve(group))
	if fg then
		table.insert(out, ("  --%s-fg: %s;"):format(group, hex(fg)))
	end
	if bg then
		table.insert(out, ("  --%s-bg: %s;"):format(group, hex(bg)))
	end
end
local component = require("lualine").get_config().options.component_separators
table.insert(out, ("  --component-separator: %s;"):format(css_string(component.right)))
for _, mode in ipairs({ "normal", "command", "visual" }) do
	table.insert(out, lualine(mode))
end
table.insert(out, "  .highlight {")
for _, capture in ipairs(captures) do
	local css = declarations(resolve("@" .. capture))
	if #css > 0 then
		table.insert(out, ("    .%s { %s; }"):format(capture:gsub("%.", "-"), table.concat(css, "; ")))
	end
end
table.insert(out, "  }")
table.insert(out, "}")
io.write(table.concat(out, "\n") .. "\n")
